_target_: pytorch_lightning.Trainer
gpus: 1  # set -1 to train on all GPUs available, set 0 to train on CPU only
min_epochs: 1
max_epochs: 10
gradient_clip_val: 5
num_sanity_val_steps: 3
progress_bar_refresh_rate: 20
weights_summary: null
fast_dev_run: False
#default_root_dir: "lightning_logs/"
