# @package _global_

datamodule:
  use_char: False
  use_bert: True
  use_pos: False
  use_word: False
  use_emb: False
  ext_emb_path: ""
  bert: ''
  min_freq: 2
  fix_len: 20
  train_sampler_type: 'token'
  test_sampler_type: 'token'
  bucket: 32
  bucket_test: 32
  max_tokens: 5000
  max_tokens_test: 5000
  use_cache: True
  use_bert_cache: True
  max_len: 10000
  max_len_test: 10000
  root: '.'
  distributed: False
  # for PTB only. clean (-RHS-)
  clean_word: False

